import { NextRequest, NextResponse } from 'next/server'
import { dbInsertTopic, dbInsertNotification } from '@/lib/localDb'

export async function POST(req: NextRequest) {
  try {
    const secret = req.headers.get('x-webhook-secret')
    if (process.env.N8N_WEBHOOK_SECRET && secret !== process.env.N8N_WEBHOOK_SECRET) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await req.json()
    const { title, category, keywords, seo_title, priority, assignee, content } = body

    if (!title?.trim()) {
      return NextResponse.json({ error: '"title" is required' }, { status: 400 })
    }

    const kwArray: string[] | null = Array.isArray(keywords)
      ? keywords
      : typeof keywords === 'string' && keywords.trim()
        ? keywords.split(',').map((k: string) => k.trim())
        : null

    const topic = dbInsertTopic({
      title:        title.trim(),
      category:     category  || null,
      keywords:     kwArray,
      seo_title:    seo_title || null,
      priority:     priority  || 'Medium',
      assignee:     assignee  || null,
      content:      content   || null,
      status:       'Pending',
      current_team: 'content',
      deadline:     null,
    })

    dbInsertNotification({
      type:    'new_topic',
      title:   'New topic generated by n8n',
      message: `"${title.trim()}" was added to the review queue.`,
      read:    false,
    })

    return NextResponse.json({ success: true, topic }, { status: 201 })
  } catch (err) {
    console.error('[webhook/n8n]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
